### PR TITLE
Update esy.json for recent esy

### PR DESCRIPTION
**Pull request by andreypopp**
This updates esy.json for recent esy.

### CODE REVIEW

**Comment by aantron** [comment]
@andreypopp Thanks! Did you mean to commit `esy.lock.json`? I'm still not sure what to do with that file :)

**Comment by andreypopp** [comment]
@aantron yes! the idea is that if someone clones the repo they will get exactly the same versions as defined in `esy.lock.json` so they won't need to run solver and get into some state which isn't buildable (well, tbh it's rare with opam but happens too).

On CI it might makes sense to test from time to time that dependencies are solvable (by removing `esyi.lock.json` and running `esy install && esy build`).

**Comment by andreypopp** [comment]
Btw: I was able to try out `repromise_lwt` with just:
```
{
  "name": "repromise_lwt",
  "version": "1.0.0",
  "esy": {
    "build": "dune build -p repromise_lwt"
  },
  "dependencies": {
    "@opam/base-unix": "*",
    "@opam/lwt": "*",
    "@opam/repromise": "aantron/repromise",
    "@opam/result": "*",
    "@opam/dune": "*",
    "@esy-ocaml/reason": "*"
  },
  "devDependencies": {
    "@opam/merlin": "^3.0.5",
    "ocaml": "4.6.x"
  }
}
```

Fetching yet to be released repromise from github!

**Comment by aantron** [comment]
Thanks! I'll try restoring the Travis esy build as a follow-on to this PR. Would you mind PRing the `esy.json` to `repromise_lwt`? I'd be quite happy to merge it :)

**Comment by aantron** [comment]
@andreypopp BTW Repromise is released, it is `@aantron/repromise` in NPM :) https://www.npmjs.com/package/@aantron/repromise

**Comment by aantron** [comment]
Never mind, that's the JS one, you're using native, and that's not released indeed..!

**Pull request merged**
