### PR TITLE
Added map function

### PR DESCRIPTION
**Pull request by ncthbrt**

### CODE REVIEW

**Comment by aantron** [comment]
Compilation with BuckleScript from a clean repo gives:

```
  ~/repromise/test/test_promise.re 30:31-35:3

  28 ┆ }),
  29 ┆ 
  30 ┆ test("map soundness", () => {
  31 ┆     Repromise.resolve(6)
   . ┆ ...
  34 ┆     |> Repromise.map(r => r);
  35 ┆ }),
  36 ┆ 
  37 ┆ test("await", () => {
  
  This has type:
    Repromise.promise (Repromise.promise (bool,  'a),  'b)
  But somewhere wanted:
    Repromise.t (bool,  Framework.never) (defined as
      Repromise.promise (bool,  Framework.never))
  
  The incompatible parts:
    Repromise.promise (bool,  'a)
    vs
    bool
```

**Comment by ncthbrt** [comment]
Sorry. Guess that's what you get when coding past midnight. Wasn't focusing. Will fix when I get into work.

**Comment by ncthbrt** [comment]
@aantron: Should be compiling again

**Comment by aantron** [comment]
No problem, and thanks for the fix :) I'm going to set up Travis soon-ish. It should be helpful for this, but even more so for making sure things build on all the *other* build systems that each person isn't going to want to set up and test on. Just have to work through some build system bit rot that has accumulated.

**Pull request merged**
