### PR TITLE
node.fs bindings in progress

### PR DESCRIPTION
**Pull request by kennetpostigo**
Hey so these include some in progress bindings to node filesystem module. I've gone ahead and omitted arguments to a few functions that require a `Js.t` as an argument. 

So some things moving forward:
- How to get rid warnings of unused value for the bindings (odd because I don't get these in a project I have)
- How should we type `Js.t`'s from functions? Some functions have same `Js.t`, others don't.
- How should we type classes from node.fs?
- Do we need a `.rei` file if these are just going to be bindings?
- Add labels to arguments with default values for node.fs optional arguments?

### CODE REVIEW

**Comment by aantron** [comment]
> How to get rid warnings of unused value for the bindings (odd because I don't get these in a project I have)

Expose them in `.rei` or delete the `.rei.

> How should we type Js.t's from functions? Some functions have same Js.t, others don't.

We need to decide what types we want to expose out of the binding on a case-by-case basis. This is the design work in FFIs usually.

> How should we type classes from node.fs?

Not sure what this refers to. What do you mean by "type classes?"

> Do we need a .rei file if these are just going to be bindings?

If they are absolutely trivial, then no. But otherwise, `.rei` provides a nice table of contents for people that don't want to scroll through the implementation. Maybe once we have great docs, we don't need the `.rei` anymore, if we are not otherwise trying to enforce some abstractions for engineering reasons.

> Add labels to arguments with default values for node.fs optional arguments?

I think that's the only way, besides using `option('a)`.

**Comment by kennetpostigo** [comment]
> Not sure what this refers to. What do you mean by "type classes?"

What I meant was, how should we go about dealing with Javascript classes

**Comment by aantron** [comment]
> how should we go about dealing with Javascript classes

My default instinct is to create ordinary opaque Reason types for them, kind of like the binding already does for `buffer` (even though it's not exposed).

**Comment by aantron** [comment]
We don't necessarily want to expose every type to the user, for example `Buffer`. That actually might be a bad example, but I'm going to use it anyway.

There are already a bunch of Reason types for buffers, like `string`, `bytes`, and `Buffer.t`. If we expose Node buffers, it increases confusion, so maybe it's best to always translate them away right around FFI calls.

On the other hand, in the particular case of `Buffer`, there are likely to be efficiency issues from constantly translating them. I think the question of whether `Buffer` should be exposed will be answered by experience.

By the way, this is one reason to have a `.rei`: if we have some type that we don't want anyone to use, the `.rei` hides it if we don't mention it there.

**Comment by kennetpostigo** [comment]
So I added the labels, and updated the rei, but I broke the test you had because the signature of open and read changed. @aantron

**Comment by kennetpostigo** [comment]
Test passing agin :)

**Comment by kennetpostigo** [comment]
Going ahead and merging this, everything is working locally

**Comment by aantron** [comment]
Yo I'm backing this out for now, because it broke `master`. Let me know when it's ready for a second go.

**Pull request merged**
